---
ignores: # If found in path contained elements will be ignored


fileSpecs:

  package.json: # For package.json 
    json:
      force:  # Following fields will be replaced anyway
        author: "{AUTHOR_NAME} <{AUTHOR_EMAIL}> ({AUTHOR_WEB})"
        license: "{SPDX}"
        private: true
      defaults: # Following fields will be replaced if not present
        homepage: "{HOMEPAGE}"
        description: "{DESCRIPTION}"
      sortPackage: true # Nice ordering of packge items 

    addSibling: true # Add a LICENSE file in the same directory than package.json

  ".js": # All Javascript source code file
    addHeader:
      startBlock: >- 
        /**
         * @license
      lineBlock: " * "
      endBlock: >
        */

  README.md: # All README.md files
    addTrailer:
      action: addTrailer
      startBlock: "# License"
      lineBlock: ''
      endBlock: ''